import Product from './Product';

const products: Product[] = [
  {
    id: 1,
    sku: 'B001',
    name: 'The Catcher in the Rye',
    price: 10,
    type: 'book',
    weight: 0.8,
  },
  {
    id: 2,
    sku: 'B002',
    name: 'To Kill a Mockingbird',
    price: 12,
    type: 'book',
    weight: 0.9,
  },
  {
    id: 3,
    sku: 'D001',
    name: 'The Matrix',
    price: 9,
    type: 'dvd',
    size: 5,
  },
  {
    id: 4,
    sku: 'D002',
    name: 'Inception',
    price: 11,
    type: 'dvd',
    size: 7,
  },
  {
    id: 5,
    sku: 'F001',
    name: 'Sofa',
    price: 399,
    type: 'furniture',
    height: 40,
    width: 70,
    length: 200,
  },
  {
    id: 6,
    sku: 'B003',
    name: 'The Great Gatsby',
    price: 11,
    type: 'book',
    weight: 0.7,
  },
  {
    id: 7,
    sku: 'D003',
    name: 'Jurassic Park',
    price: 14,
    type: 'dvd',
    size: 9,
  },
  {
    id: 8,
    sku: 'F002',
    name: 'Dining Table',
    price: 279,
    type: 'furniture',
    height: 75,
    width: 90,
    length: 150,
  },
  {
    id: 9,
    sku: 'B004',
    name: 'The Lord of the Rings: The Fellowship of the Ring',
    price: 25,
    type: 'book',
    weight: 1.5,
  },
  {
    id: 10,
    sku: 'D004',
    name: 'Pulp Fiction',
    price: 13,
    type: 'dvd',
    size: 6,
  },
  {
    id: 11,
    sku: 'F003',
    name: 'Bed Frame',
    price: 299,
    type: 'furniture',
    height: 120,
    width: 180,
    length: 200,
  },
  {
    id: 12,
    sku: 'B005',
    name: 'The Hobbit',
    price: 17,
    type: 'book',
    weight: 1.2,
  },
  {
    id: 13,
    sku: 'D005',
    name: 'The Godfather',
    price: 12,
    type: 'dvd',
    size: 8,
  },
  {
    id: 14,
    sku: 'F004',
    name: 'Wardrobe',
    price: 349,
    type: 'furniture',
    height: 180,
    width: 100,
    length: 50,
  },
  {
    id: 15,
    sku: 'B006',
    name: 'The Great Gatsby',
    price: 11,
    type: 'book',
    weight: 0.7,
  },
  {
    id: 16,
    sku: 'D006',
    name: 'The Shawshank Redemption',
    price: 9,
    type: 'dvd',
    size: 4,
  },
  {
    id: 17,
    sku: 'F005',
    name: 'Bookshelf',
    price: 99,
    type: 'furniture',
    height: 120,
    width: 60,
    length: 30,
  },
];

export default products;
